version: '3'
services: 
  app:
    build: .
    volumes: 
      - .:/usr/src/app
    ports:
      - "3333:3000"
      - "35729:35729"
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=pjapp.docker
      - PYTHONUNBUFFERED=1