#!/bin/bash

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
S3_BUCKETNAME=adventure.pacificjamboree.ca

export AWS_CONFIG_FILE="$HOME/.aws/config"
export AWS_PROFILE=pj
export AWS_REGION=ca-central-1

if [ $CURRENT_BRANCH != "master" ] ; then
  echo "Not on master branch; stopping."
  exit 1
else
  echo 'Syncing build folder to S3'
  aws s3 sync build/ s3://$S3_BUCKETNAME --delete --cache-control max-age=31536000,public && \
  aws s3 cp s3://$S3_BUCKETNAME/service-worker.js s3://$S3_BUCKETNAME/service-worker.js --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type application/javascript --acl public-read
  aws s3 cp s3://$S3_BUCKETNAME/index.html s3://$S3_BUCKETNAME/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read 

  echo 'Invalidating CloudFront cache' && \
  aws cloudfront create-invalidation --distribution-id E305U167B57NUX --paths /\*
fi
