#!/bin/bash

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
export AWS_CONFIG_FILE="$HOME/.aws/config"
export AWS_PROFILE=pj
export AWS_REGION=ca-central-1

if [ $CURRENT_BRANCH != "master" ] ; then
  echo "Not on master branch; stopping."
  exit 1
else
  echo 'Syncing build folder to S3'
  aws s3 sync build/ s3://adventure.pacificjamboree.ca && \
  echo 'Invalidating CloudFront cache' && \
  aws cloudfront create-invalidation --distribution-id E305U167B57NUX --paths '/*'
fi
